
export const LOADING = "LOADING"
export const UPDATESTATUS = "UPDATESTATUS"
export const TOKBOXSESSION = "TOKBOXSESSION"
export const CREATEMEETING = "CREATEMEETING"

export const USER_REQUEST = "USER_REQUEST"
export const PENDING_MEETING_LIST = "PENDING_MEETING_LIST"
export const PENDING_MEETING_UPDATE_STATUS = "PENDING_MEETING_UPDATE_STATUS"
//NEW API
export const MEETING_RECORDING = "MEETING_RECORDING"
export const USERS_JOINS_MEETING = "USERS_JOINS_MEETING"
export const GET_JOIN_USERS_LIST = "GET_JOIN_USERS_LIST"
